services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      - ./uploads:/uploads
      - ../ML:/app/ML  # Mount ML directory inside container

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  uploads: